#!/bin/sh

if [ $# -gt 0 ]; then

	# ARGS has one argument per line
	ARGS=`echo $@ | xargs printf '%s\n'`

	# INVALID_ARGS is those ARGS that don't look like [path/]library.a
	INVALID_ARGS=`echo "$ARGS" | grep -v '\b[A-Za-z0-9_]\+\.a$'`
	if [ -n "$INVALID_ARGS" ] ; then
		printf "Error: all arguments must be paths to .a files: \n%s\n" \
			"${INVALID_ARGS}" >&2
		exit 1
	fi

	# foo/foo.h -> filter_extension_foo
	EXTS=`echo "$ARGS" | sed -e 's!.*/!filter_extension_!' -e 's!.a$!!'`

	# filter_extension_foo -> [\t]filter_extension_foo,
	DECLARATIONS=`echo "$EXTS" | sed -e 's!^!\t!' -e 's!$!,!'`

	# filter_extension_foo -> [\t]&filter_extension_foo,
	ARRAY=`echo "$EXTS" | sed -e 's!^!\t\&!' -e 's!$!,!'`
fi

echo '/* Automatically generated by generate-list-objects-filter-extensions.sh */'
echo
echo '#include "git-compat-util.h"'
echo '#include "list-objects-filter-extensions.h"'
echo

if [ $# -gt 0 ]; then
	echo 'extern const struct filter_extension'
	echo "${DECLARATIONS%?}"
	echo ';'
	echo
fi

echo 'const struct filter_extension *filter_extensions[] = {'
echo "${ARRAY}"
echo '\tNULL,'
echo '};'