/* Automatically generated by generate-list-objects-filter-extensions.sh */

#include "git-compat-util.h"
#include "list-objects-filter-extensions.h"

extern const struct filter_extension
	filter_extension_rand_cpp,
	filter_extension_rand
;

const struct filter_extension *filter_extensions[] = {
	&filter_extension_rand_cpp,
	&filter_extension_rand,
	NULL,
};
